### ISSUE TITLE
Activity com.example.thermaldemo.MainActivity has leaked IntentReceiver

### ISSUE THREAD

**Issue by maheshbhattaraai** [kakzaki/blue_thermal_printer#6]
```
D/ActivityThread( 6209): ACT-DESTROY_ACTIVITY handled : 1 / android.os.BinderProxy@3b0942ce
E/ActivityThread( 6209): Activity com.example.thermaldemo.MainActivity has leaked IntentReceiver id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1$1@d37b3f4 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 6209): android.app.IntentReceiverLeaked: Activity com.example.thermaldemo.MainActivity has leaked IntentReceiver id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1$1@d37b3f4 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 6209):        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:932)
E/ActivityThread( 6209):        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:703)
E/ActivityThread( 6209):        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1731)
E/ActivityThread( 6209):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1711)
E/ActivityThread( 6209):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1705)
E/ActivityThread( 6209):        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:488)
E/ActivityThread( 6209):        at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1.onListen(BlueThermalPrinterPlugin.java:620)
E/ActivityThread( 6209):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/ActivityThread( 6209):        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/ActivityThread( 6209):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/ActivityThread( 6209):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/ActivityThread( 6209):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread( 6209):        at android.os.MessageQueue.next(MessageQueue.java:143)
E/ActivityThread( 6209):        at android.os.Looper.loop(Looper.java:146)
E/ActivityThread( 6209):        at android.app.ActivityThread.main(ActivityThread.java:5529)
E/ActivityThread( 6209):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 6209):        at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread( 6209):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
E/ActivityThread( 6209):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
I/Process ( 6209): Sending signal. PID: 6209 SIG: 9
Lost connection to device.
```

> I am running the example app. Whenever  i pressed the button connect to the device the app terminates unexpectedly. Thank You

**Comment by kakzaki** [comment]
please upgrade to blue_thermal_printer 1.0.8
