### ISSUE TITLE
My app was just idling and then crash!

### ISSUE THREAD

**Issue by DowsingUK** [kakzaki/blue_thermal_printer#72]
MainActivity has leaked IntentReceiver id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1$1@fefd986 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.fendercorp.self_checkout.MainActivity has leaked IntentReceiver id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1$1@fefd986 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1516)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1489)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1477)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
        at id.kakzaki.blue_thermal_printer.BlueThermalPrinterPlugin$1.onListen(BlueThermalPrinterPlugin.java:720)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by kakzaki** [comment]
This thread has been closed since there has not been any recent activity. If you are still experiencing a similar issue, please open a new bug, including the output of flutter doctor -v and a minimal reproduction of the issue.
